version: "3.8"

services:
  log-generator:
    build: ./log-generator
    container_name: log_generator_service
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.5
    container_name: loki_service
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail_service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana_service
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - loki
    restart: unless-stopped

  vector-db:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant_service
    ports:
      - "6333:6333"
      - "6334:6334"
    # Uncomment the next line to persist Qdrant data locally
    # volumes:
    #   - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped 